[package]
name = "myproject-client"
description = "Generated client for myproject"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = {workspace = true }
solana-program = { workspace = true }
thiserror = { workspace = true }
num-derive = "0.4"
num-traits = "0.2"